import { Component, OnDestroy, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { OrdersActiveComponent } from '../orders-active/orders-active.component';
import { DemoBannerComponent } from './demo-banner.component';
import { DemoSessionService } from '../../services/demo-session.service';
import { BackofficeEventService } from '../../services/backoffice-event.service';
import { RestaurantOrderService } from '../../services/restaurant-order.service';

@Component({selector:'app-demo-restaurant-page',standalone:true,imports:[CommonModule,RouterLink,OrdersActiveComponent,DemoBannerComponent],template:`<app-demo-banner/><div *ngIf="loading" class="demo-state">Apertura dashboard demo…</div><section *ngIf="expired" class="demo-expired"><h1>La demo è terminata</h1><p>Avvia una nuova sessione per continuare.</p><a routerLink="/demo">Avvia nuova demo</a></section><main *ngIf="ready" class="demo-dashboard"><aside *ngIf="guideOpen" class="demo-guide"><button aria-label="Chiudi guida" (click)="guideOpen=false">×</button><small>GUIDA RAPIDA</small><h2>{{completed?'Questo era un solo tavolo.':received?'2. Ordine ricevuto!':'1. Fai un ordine'}}</h2><p>{{completed?'Immagina WaiterO nel tuo locale.':received?'Quello che stai vedendo è ciò che vedrebbe il personale del tuo locale. 3. Apri l’ordine e prova a gestirlo.':'Scansiona il QR dall’hub e ordina qualcosa dal tuo smartphone.'}}</p><a *ngIf="!received" routerLink="/demo">Mostra il QR</a><a *ngIf="completed" routerLink="/" fragment="contatti">Richiedi una demo</a></aside><header class="demo-dashboard-head"><div><small>Dashboard reale</small><h1>Osteria WaiterO</h1></div><a routerLink="/demo">Hub demo</a></header><app-orders-active/></main>`,styleUrl:'./demo.component.scss'})
export class DemoRestaurantPageComponent implements OnInit,OnDestroy{private route=inject(ActivatedRoute);private sessions=inject(DemoSessionService);private events=inject(BackofficeEventService);private orders=inject(RestaurantOrderService);private sub?:Subscription;loading=true;expired=false;ready=false;received=false;completed=false;guideOpen=true;ngOnInit():void{this.sessions.current(this.route.snapshot.queryParamMap.get('s')).subscribe({next:()=>{this.ready=true;this.loading=false;this.orders.getActiveOrderSummaries().subscribe(values=>this.received=values.length>0);this.events.start();this.sub=this.events.ordersUpdated$.subscribe(e=>{if(e.payload?.orderId)this.received=true;if(e.payload?.status==='PAGATO')this.completed=true;});},error:()=>{this.loading=false;this.expired=true;}});}ngOnDestroy():void{this.sub?.unsubscribe();this.events.stop();}}
